"""empty message

Revision ID: 2c0293fe2076
Revises: d1f7b2af80de
Create Date: 2025-04-13 01:16:48.619669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0293fe2076'
down_revision: Union[str, None] = 'd1f7b2af80de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_username', sa.String(), nullable=True))
    op.drop_column('user', 'telegram_id')
    op.add_column('user_department', sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_department', 'is_admin')
    op.add_column('user', sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'telegram_username')
    # ### end Alembic commands ###
