"""empty message

Revision ID: 311429cb1a9c
Revises: d1f7b2af80de
Create Date: 2025-04-13 00:54:24.537949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311429cb1a9c'
down_revision: Union[str, None] = 'd1f7b2af80de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_username', sa.String(length=32), nullable=True))
    op.drop_column('user', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'telegram_username')
    # ### end Alembic commands ###
