"""empty message

Revision ID: 63b81013b5b8
Revises: ece8251dd435
Create Date: 2025-04-12 19:46:02.235155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63b81013b5b8'
down_revision: Union[str, None] = 'ece8251dd435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE doc_sign_status AS ENUM ('in_progress', 'signed', 'rejected')")

    # Затем изменяем таблицу
    op.alter_column('document', 'status',
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.Enum('in_progress', 'signed', 'rejected', name='doc_sign_status'),
                    postgresql_using='status::doc_sign_status')
    op.drop_table('document_signature')
    op.add_column('stage_signer', sa.Column('signature_type', sa.String(length=50), nullable=True))
    op.drop_column('stage_signer', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_signer', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('stage_signer', 'signature_type')
    op.alter_column('document', 'status',
                    existing_type=sa.Enum('in_progress', 'signed', 'rejected', name='doc_sign_status'),
                    type_=sa.VARCHAR(length=20),
                    postgresql_using='status::text')
    op.execute("DROP TYPE doc_sign_status")
    op.create_table('document_signature',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signature_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('signed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('stage_signer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('signature_data', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stage_signer_id'], ['stage_signer.id'], name='document_signature_stage_signer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_signature_pkey')
    )
    # ### end Alembic commands ###
