"""empty message

Revision ID: 74a9e87413ed
Revises: c39e8c530d51
Create Date: 2025-04-13 07:53:17.313441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a9e87413ed'
down_revision: Union[str, None] = 'c39e8c530d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_organization_organization_id_fkey', 'user_organization', type_='foreignkey')
    op.create_foreign_key(None, 'user_organization', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_organization', type_='foreignkey')
    op.create_foreign_key('user_organization_organization_id_fkey', 'user_organization', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###
