"""empty message

Revision ID: 938e75312a6d
Revises: 7a574b8177f1
Create Date: 2025-04-12 19:19:34.030741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938e75312a6d'
down_revision: Union[str, None] = '7a574b8177f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_sign_stage', sa.Column('is_current', sa.Boolean(), nullable=False))
    op.drop_column('document', 'current_stage_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('current_stage_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('doc_sign_stage', 'is_current')
    # ### end Alembic commands ###
