"""empty message

Revision ID: c39e8c530d51
Revises: f9e9e965decb
Create Date: 2025-04-13 07:40:40.821535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39e8c530d51'
down_revision: Union[str, None] = 'f9e9e965decb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('department_name_key', 'department', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('department_name_key', 'department', ['name'])
    # ### end Alembic commands ###
