"""empty message

Revision ID: dfb621ba0d82
Revises: 938e75312a6d
Create Date: 2025-04-12 19:23:24.537291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb621ba0d82'
down_revision: Union[str, None] = '938e75312a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'document', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'organization_id')
    # ### end Alembic commands ###
