"""empty message

Revision ID: eae267670ad2
Revises: 63b81013b5b8
Create Date: 2025-04-12 20:11:57.511912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eae267670ad2'
down_revision: Union[str, None] = '63b81013b5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_department_id_fkey', 'document', type_='foreignkey')
    op.drop_column('document', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('document_department_id_fkey', 'document', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###
