"""empty message

Revision ID: ece8251dd435
Revises: dfb621ba0d82
Create Date: 2025-04-12 19:33:03.780535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece8251dd435'
down_revision: Union[str, None] = 'dfb621ba0d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_signature', sa.Column('stage_signer_id', sa.Integer(), nullable=False))
    op.add_column('document_signature', sa.Column('signature_data', sa.String(length=500), nullable=True))
    op.drop_constraint('document_signature_user_id_fkey', 'document_signature', type_='foreignkey')
    op.drop_constraint('document_signature_document_id_fkey', 'document_signature', type_='foreignkey')
    op.create_foreign_key(None, 'document_signature', 'stage_signer', ['stage_signer_id'], ['id'])
    op.drop_column('document_signature', 'document_id')
    op.drop_column('document_signature', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_signature', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('document_signature', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_signature', type_='foreignkey')
    op.create_foreign_key('document_signature_document_id_fkey', 'document_signature', 'document', ['document_id'], ['id'])
    op.create_foreign_key('document_signature_user_id_fkey', 'document_signature', 'user', ['user_id'], ['id'])
    op.drop_column('document_signature', 'signature_data')
    op.drop_column('document_signature', 'stage_signer_id')
    # ### end Alembic commands ###
