"""empty message

Revision ID: f9e9e965decb
Revises: ac6bc3a0f3cf
Create Date: 2025-04-13 06:30:50.300921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e9e965decb'
down_revision: Union[str, None] = 'ac6bc3a0f3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_signer', sa.Column('digital_signature', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_signer', 'digital_signature')
    # ### end Alembic commands ###
